### ISSUE TITLE
Module_six_moves_urllib_parse' object has no attribute 'urlencode

### ISSUE THREAD

**Issue by pepedocs** [GoogleCloudPlatform/compute-getting-started-python#9]
Hi, I got the following error while trying to run this example;

OS: osx
Client: google-api-python-client-1.4.1
Python: 2.7

mymac2:compute-getting-started-python josecueto$ python main.py
What is your project ID? myproject
What zone would you like to use? [us-central1-f] asia-east1-a
Creating instance.
Traceback (most recent call last):
  File "main.py", line 178, in <module>
    main()
  File "main.py", line 174, in main
    run(project, zone, instance_name)
  File "main.py", line 144, in run
    operation = create_instance(compute, project, zone, instance_name)
  File "main.py", line 103, in create_instance
    body=config).execute()
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/googleapiclient/http.py", line 722, in execute
    body=self.body, headers=self.headers)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 540, in new_request
    self._refresh(request_orig)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 768, in _refresh
    self._do_refresh_request(http_request)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 794, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 734, in _generate_refresh_request_body
    body = urllib.parse.urlencode({
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlencode'

**Comment by jonparrott** [comment]
This can often happen with outdated versions of ``six`` in ``site-packages``. I highly recommend using a virtualenv:

``
sudo pip install virtualenv
virtualenv env
source env/bin/activate
pip install google-api-python-client
...
```

Let me know if this fixes it for you.

**Comment by pepedocs** [comment]
Hi ,

Thanks so much, that fixed it.

Cheers,
Jose

**Comment by jonparrott** [comment]
No problem, glad it solved your issue.
